teams = [
"Manchester City",
"Manchester United",
"Chelsea",
"Tottenham Hotspur",
"Liverpool",
"Liverpool",
"Tottenham Hotspur",
"Manchester United",
"Manchester City",
"Manchester City",
"Manchester United",
"Liverpool",
"Liverpool",
"Manchester United",
"Manchester City",
"Manchester City",
"Manchester City",
"Manchester City",
"Liverpool",
"Leicester City",
"Manchester City",
"Manchester United",
"Liverpool",
"Manchester United",
"Leicester City",
"Chelsea",
"Liverpool",
"Arsenal",
"Manchester City",
"Manchester City",
"Manchester United",
"Chelsea",
"Aston Villa",
"Newcastle United",
"Manchester City",
"Chelsea",
"Leicester City",
"Leicester City",
"Chelsea",
"Manchester City",
"Manchester United",
"Manchester United",
"Everton",
"Liverpool",
"Chelsea",
"Arsenal",
"Manchester United",
"Tottenham Hotspur",
"Arsenal",
"Chelsea",
"Chelsea",
"Wolverhampton Wanderers",
"Manchester City",
"Everton",
"Liverpool",
"Chelsea",
"Manchester City",
"Brentford",
"Aston Villa",
"Manchester City",
"West Ham United",
"Tottenham Hotspur",
"Leeds United",
"Tottenham Hotspur",
"Everton",
"Chelsea",
"Aston Villa",
"Chelsea",
"Liverpool",
"Liverpool",
"Wolverhampton Wanderers",
"Arsenal",
"Leicester City",
"Manchester United",
"Chelsea",
"Crystal Palace",
"Tottenham Hotspur",
"Everton",
"Tottenham Hotspur",
"Chelsea",
"Tottenham Hotspur",
"Arsenal",
"Everton",
"Manchester United",
"Manchester United",
"Manchester United",
"Tottenham Hotspur",
"Everton",
"Liverpool",
"Arsenal",
"West Ham United",
"Manchester United",
"Leicester City",
"Wolverhampton Wanderers",
"Arsenal",
"Arsenal",
"Newcastle United",
"Manchester United",
"Tottenham Hotspur",
"Newcastle United",
"Everton",
"Liverpool",
"Leeds United",
"Newcastle United",
"West Ham United",
"Tottenham Hotspur",
"Manchester United",
"Liverpool",
"Watford",
"Aston Villa",
"Wolverhampton Wanderers",
"Aston Villa",
"Wolverhampton Wanderers",
"Manchester City",
"Chelsea",
"Crystal Palace",
"Watford",
"Watford",
"Leicester City",
"Leeds United",
"Newcastle United",
"West Ham United",
"Brentford",
"Burnley",
"West Ham United",
"Arsenal",
"Brighton & Hove Albion",
"Leicester City",
"Leeds United",
"Southampton",
"West Ham United",
"Burnley",
"Aston Villa",
"Watford",
"Everton",
"West Ham United",
"Tottenham Hotspur",
"Manchester United",
"Liverpool",
"Chelsea",
"Tottenham Hotspur",
"Wolverhampton Wanderers",
"Everton",
"West Ham United",
"Leicester City",
"Wolverhampton Wanderers",
"Newcastle United",
"Tottenham Hotspur",
"Brighton & Hove Albion",
"Arsenal",
"West Ham United",
"Aston Villa",
"Leicester City",
"Everton",
"Manchester United",
"Tottenham Hotspur",
"Manchester City",
"Wolverhampton Wanderers",
"Tottenham Hotspur",
"Wolverhampton Wanderers",
"Arsenal",
"Chelsea",
"Burnley",
"Manchester United",
"Burnley",
"West Ham United",
"Everton",
"Liverpool",
"Leicester City",
"Leeds United",
"Leicester City",
"Wolverhampton Wanderers",
"Leeds United",
"Aston Villa",
"Leicester City",
"West Ham United",
"Leicester City",
"Aston Villa",
"Aston Villa",
"Wolverhampton Wanderers",
"Leeds United",
"Leicester City",
"Tottenham Hotspur",
"Brighton & Hove Albion",
"Southampton",
"Burnley",
"Everton",
"Manchester United",
"Aston Villa",
"Newcastle United",
"Burnley",
"Chelsea",
"Leeds United",
"Aston Villa",
"Crystal Palace",
"West Ham United",
"Leicester City",
"Southampton",
"Leicester City",
"Norwich City",
"Arsenal",
"Southampton",
"Everton",
"Everton",
"Crystal Palace",
"Tottenham Hotspur",
"West Ham United",
"Aston Villa",
"Everton",
"Everton",
"Arsenal",
"Leeds United",
"Wolverhampton Wanderers",
"West Ham United",
"Brighton & Hove Albion",
"Everton",
"Brighton & Hove Albion",
"Aston Villa",
"Brighton & Hove Albion",
"Newcastle United",
"Southampton",
"Everton",
"West Ham United",
"Watford",
"Everton",
"West Ham United",
"Everton",
"Everton",
"Aston Villa",
"Arsenal",
"Tottenham Hotspur",
"Southampton",
"Wolverhampton Wanderers",
"Arsenal",
"Norwich City",
"Manchester United",
"Arsenal",
"Norwich City",
"Southampton",
"Watford",
"Norwich City",
"Southampton",
"Burnley",
"Southampton",
"Aston Villa",
"Liverpool",
"Brentford",
"Aston Villa",
"Newcastle United",
"Arsenal",
"Crystal Palace",
"Crystal Palace",
"Newcastle United",
"Burnley",
"Arsenal",
"Burnley",
"Southampton",
"West Ham United",
"Brighton & Hove Albion",
"Norwich City",
"Leeds United",
"Leicester City",
"Burnley",
"Leicester City",
"Southampton",
"Newcastle United",
"Aston Villa",
"West Ham United",
"Norwich City",
"Brighton & Hove Albion",
"Watford",
"Tottenham Hotspur",
"Norwich City",
"Brighton & Hove Albion",
"Newcastle United",
"Watford",
"Crystal Palace",
"Brentford",
"Crystal Palace",
"Arsenal",
"Everton",
"Liverpool",
"Wolverhampton Wanderers",
"Aston Villa",
"Arsenal",
"Norwich City",
"Burnley",
"Brentford",
"Aston Villa",
"Crystal Palace",
"Everton",
"Burnley",
"Chelsea",
"Aston Villa",
"Arsenal",
"Newcastle United",
"Wolverhampton Wanderers",
"Brighton & Hove Albion",
"Brighton & Hove Albion",
"Arsenal",
"Leeds United",
"Southampton",
"Newcastle United",
"Crystal Palace",
"Norwich City",
"Leicester City",
"Brighton & Hove Albion",
"Crystal Palace",
"Brentford",
"Burnley",
"Crystal Palace",
"Watford",
"Watford",
"Leeds United",
"Newcastle United",
"Burnley",
"Watford",
"Crystal Palace",
"Everton",
"Newcastle United",
"Brighton & Hove Albion",
"Crystal Palace",
"Crystal Palace",
"Watford",
"West Ham United",
"Liverpool",
"Manchester City",
"Tottenham Hotspur",
"Leicester City",
"Aston Villa",
"Manchester United",
"Chelsea",
"Everton",
"Burnley",
"Arsenal",
"West Ham United",
"West Ham United",
"Crystal Palace",
"Tottenham Hotspur",
"Newcastle United",
"Manchester United",
"Wolverhampton Wanderers",
"Chelsea",
"Watford",
"Leeds United",
"Manchester City",
"Norwich City",
"Aston Villa",
"Brighton & Hove Albion",
"Newcastle United",
"Everton",
"Manchester United",
"Liverpool",
"Southampton",
"Southampton",
"West Ham United",
]
