league = [
"Ligue 1 Uber Eats",
"Bundesliga",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Premier League",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League"
]