names = [
    "Lionel Messi",
    "Robert Lewandowski",
    "Kylian Mbappe",
    "Kevin De Bruyne",
    "Neymar Jr",
    "Cristiano Ronaldo",
    "N'Golo Kante",
    "Harry Kane",
    "Joshua Kimmich",
    "Mohamed Salah",
    "Sadio Mane",
    "Virgil van Dijk",
    "Casemiro",
    "Heung Min Son",
    "Karim Benzema",
    "Erling Haaland",
    "Bruno Fernandes",
    "Raheem Sterling",
    "Romelu Lukaku",
    "Toni Kroos",
    "Luis Suarez",
    "Sergio Ramos",
    "Ruben Dias",
    "Jadon Sancho",
    "Trent Alexander-Arnold",
    "Frenkie de Jong",
    "Andrew Robertson",
    "Paulo Dybala",
    "Leon Goretzka",
    "Marquinhos",
    "Marco Verratti",
    "Paul Pogba",
    "Ciro Immobile",
    "Thomas Muller",
    "Angel Di Maria",
    "Luka Modric",
    "Milan Skriniar",
    "Rodri",
    "Marcos Llorente",
    "Bernardo Silva",
    "Kingsley Coman",
    "Aymeric Laporte",
    "Joao Cancelo",
    "Fabinho",
    "Jamie Vardy",
    "Gerard Moreno",
    "Riyad Mahrez",
    "Raphael Varane",
    "Kalidou Koulibaly",
    "Lorenzo Insigne",
    "Parejo",
    "Sergio Busquets",
    "Thiago",
    "Jordi Alba",
    "Mats Hummels",
    "Giorgio Chiellini",
    "Pierre-Emerick Aubameyang",
    "Matthijs de Ligt",
    "Achraf Hakimi",
    "Marcus Rashford",
    "Lautaro Martinez",
    "Oyarzabal",
    "Wilfred Ndidi",
    "Sergej Milinkovic-Savic",
    "Serge Gnabry",
    "Jorginho",
    "Carvajal",
    "Memphis Depay",
    "Roberto Firmino",
    "Stefan de Vrij",
    "Antoine Griezmann",
    "Koke",
    "Pierre-Emerick Aubameyang",
    "Kyle Walker",
    "Marco Reus",
    "İlkay Gundoğan",
    "Leonardo Bonucci",
    "Eden Hazard",
    "Edinson Cavani",
    "David Silva",
    "Thiago Silva",
    "Alejandro Gomez",
    "Jan Oblak",
    "Marc-Andre ter Stegen",
    "Manuel Neuer",
    "Gianluigi Donnarumma",
    "Alisson",
    "Ederson",
    "Thibaut Courtois",
    "Keylor Navas",
    "Wojciech Szczęsny",
    "Hugo Lloris",
    "Koen Casteels",
    "Samir Handanovič",
    "Peter Gulácsi",
    "Yann Sommer",
    "Kasper Schmeichel",
    "De Gea",
    "Phil Foden",
    "Leroy Sane",
]
