teams = [
"Paris Saint-Germain",
"FC Bayern München",
"Paris Saint-Germain",
"Manchester City",
"Paris Saint-Germain",
"Manchester United",
"Chelsea",
"Tottenham Hotspur",
"FC Bayern München",
"Liverpool",
"Liverpool",
"Liverpool",
"Real Madrid",
"Tottenham Hotspur",
"Real Madrid",
"Borussia Dortmund",
"Manchester United",
"Manchester City",
"Chelsea",
"Real Madrid",
"Atlético de Madrid",
"Paris Saint-Germain",
"Manchester City",
"Manchester United",
"Liverpool",
"FC Barcelona",
"Liverpool",
"Piemonte Calcio",
"FC Bayern München",
"Paris Saint-Germain",
"Paris Saint-Germain",
"Manchester United",
"Latium",
"FC Bayern München",
"Paris Saint-Germain",
"Real Madrid",
"Inter",
"Manchester City",
"Atlético de Madrid",
"Manchester City",
"FC Bayern München",
"Manchester City",
"Manchester City",
"Liverpool",
"Leicester City",
"Villarreal CF",
"Manchester City",
"Manchester United",
"Napoli",
"Napoli",
"Villarreal CF",
"FC Barcelona",
"Liverpool",
"FC Barcelona",
"Borussia Dortmund",
"Piemonte Calcio",
"FC Barcelona",
"Piemonte Calcio",
"Paris Saint-Germain",
"Manchester United",
"Inter",
"Real Sociedad",
"Leicester City",
"Latium",
"FC Bayern München",
"Chelsea",
"Real Madrid",
"FC Barcelona",
"Liverpool",
"Inter",
"Atlético de Madrid",
"Atlético de Madrid",
"Arsenal",
"Manchester City",
"Borussia Dortmund",
"Manchester City",
"Piemonte Calcio",
"Real Madrid",
"Manchester United",
"Real Sociedad",
"Chelsea",
"Sevilla FC",
"Aston Villa",
"Newcastle United",
"Manchester City",
"Chelsea",
"Milan",
"Milan",
"RB Leipzig",
"Sevilla FC",
"Inter",
"FC Bayern München",
"Real Betis",
"Atlético de Madrid",
"Leicester City",
"Inter",
"Chelsea",
"Leicester City",
"Borussia Dortmund",
"Chelsea",
]