teams = [
"Paris Saint-Germain",
"FC Bayern München",
"Paris Saint-Germain",
"Manchester City",
"Paris Saint-Germain",
"Manchester United",
"Chelsea",
"Tottenham Hotspur",
"FC Bayern München",
"Liverpool",
"Liverpool",
"Liverpool",
"Real Madrid",
"Tottenham Hotspur",
"Real Madrid",
"Borussia Dortmund",
"Manchester United",
"Manchester City",
"Chelsea",
"Real Madrid",
"Atlético de Madrid",
"Paris Saint-Germain",
"Manchester City",
"Manchester United",
"Liverpool",
"FC Barcelona",
"Liverpool",
"Juventus",
"FC Bayern München",
"Paris Saint-Germain",
"Paris Saint-Germain",
"Manchester United",
"Latium",
"FC Bayern München",
"Paris Saint-Germain",
"Real Madrid",
"Inter",
"Manchester City",
"Atlético de Madrid",
"Manchester City",
"FC Bayern München",
"Manchester City",
"Manchester City",
"Liverpool",
"Leicester City",
"Villarreal CF",
"Manchester City",
"Manchester United",
"Napoli",
"Napoli",
"Villarreal CF",
"FC Barcelona",
"Liverpool",
"FC Barcelona",
"Borussia Dortmund",
"Juventus",
"FC Barcelona",
"Juventus",
"Paris Saint-Germain",
"Manchester United",
"Inter",
"Real Sociedad",
"Leicester City",
"Latium",
"FC Bayern München",
"Chelsea",
"Real Madrid",
"FC Barcelona",
"Liverpool",
"Inter",
"Atlético de Madrid",
"Atlético de Madrid",
"Arsenal",
"Manchester City",
"Borussia Dortmund",
"Manchester City",
"Juventus",
"Real Madrid",
"Manchester United",
"Real Sociedad",
"Chelsea",
"Sevilla FC",
"Atlético de Madrid",
"FC Barcelona",
"FC Bayern München",
"Paris Saint-Germain",
"Liverpool",
"Manchester City",
"Real Madrid",
"Paris Saint-Germain",
"Piemonte Calcio",
"Tottenham Hotspur",
"VfL Wolfsburg",
"Inter",
"RB Leipzig",
"Borussia Mönchengladbach",
"Leicester City",
"Manchester United",
"Manchester City",
"FC Bayern München"
]
