teams = [
"Paris Saint-Germain",
"FC Bayern München",
"Paris Saint-Germain",
"Manchester City",
"Paris Saint-Germain",
"Manchester United",
"Chelsea",
"Tottenham Hotspur",
"FC Bayern München",
"Liverpool",
"FC Bayern München",
"Liverpool",
"Real Madrid",
"Tottenham Hotspur",
"Real Madrid",
"Manchester City",
"Manchester United",
"Chelsea",
"Chelsea",
"Real Madrid",
"Atlético de Madrid",
"Paris Saint-Germain",
"Manchester City",
"Manchester United",
"Liverpool",
"FC Barcelona",
"Liverpool",
"Juventus",
"FC Bayern München",
"Paris Saint-Germain",
"Paris Saint-Germain",
"Manchester United",
"Latium",
"FC Bayern München",
"Paris Saint-Germain",
"Real Madrid",
"Inter",
"Manchester City",
"Atlético de Madrid",
"Manchester City",
"FC Bayern München",
"Manchester City",
"Manchester City",
"Liverpool",
"Leicester City",
"Villarreal CF",
"Manchester City",
"Manchester United",
"Napoli",
"Napoli",
"Villarreal CF",
"FC Barcelona",
"Liverpool",
"FC Barcelona",
"Borussia Dortmund",
"Juventus",
"Chelsea",
"Juventus",
"Paris Saint-Germain",
"Manchester United",
"Inter",
"Real Sociedad",
"Leicester City",
"Latium",
"FC Bayern München",
"Chelsea",
"Real Madrid",
"FC Barcelona",
"Liverpool",
"Inter",
"Atlético de Madrid",
"Atlético de Madrid",
"Arsenal",
"Manchester City",
"Borussia Dortmund",
"Manchester City",
"Juventus",
"Real Madrid",
"Manchester United",
"Real Sociedad",
"Chelsea",
"Sevilla FC",
"Aston Villa",
"Newcastle United",
"Manchester City",
"Chelsea",
"Milan",
"Milan",
"RB Leipzig",
"Sevilla FC",
"Inter",
"FC Bayern München",
"Real Betis",
"Atlético de Madrid",
"Leicester City",
"Inter",
"Chelsea",
"Leicester City",
"Borussia Dortmund",
"Chelsea",
"Eintracht Frankfurt",
"Atlético de Madrid",
"Atlético de Madrid",
"Borussia Mönchengladbach",
"Manchester City",
"Manchester United",
"FC Bayern München",
"Atlético de Madrid",
"Manchester United",
"Bergamo Calcio",
"Everton",
"AS Monaco",
"Ajax",
"Latium",
"Real Madrid",
"RC Celta",
"Atlético de Madrid",
"Sevilla FC",
"Liverpool",
"Paris Saint-Germain",
"Napoli",
"FC Barcelona",
"Sevilla FC",
"Milan",
"Inter",
"Olympiacos CFP",
"Atlético de Madrid",
"Sevilla FC",
"Real Madrid",
"Juventus",
"Chelsea",
"FC Barcelona",
"Arsenal",
"Liverpool",
"Manchester United",
"Real Madrid",
"Paris Saint-Germain",
"Real Sociedad",
"Bergamo Calcio",
"Real Madrid",
"FC Bayern München",
"RB Leipzig",
"TSG Hoffenheim",
"Bergamo Calcio",
"Atlético de Madrid",
"Tottenham Hotspur",
"Atlético de Madrid",
"Valencia CF",
"Arsenal",
"Chelsea",
"Sevilla FC",
"Chelsea",
"Wolverhampton Wanderers",
"Manchester City",
"Roma FC",
"Paris Saint-Germain",
"Juventus",
"AS Monaco",
"Everton",
"Latium",
"Sporting CP",
"Liverpool",
"Juventus",
"Roma FC",
"Napoli",
"Juventus",
"Real Betis",
"Athletic Club",
"Al Ahli",
"Chelsea",
"Milan",
"Borussia Dortmund",
"LAFC",
"Manchester City",
"Olympique Lyonnais",
"Olympique Lyonnais",
"Sevilla FC",
"Brentford",
"Aston Villa",
"FC Barcelona",
"RB Leipzig",
"Villarreal CF",
"Manchester City",
"Real Madrid",
"West Ham United",
"Tottenham Hotspur",
"FC Bayern München",
"Real Sociedad",
"Leeds United",
"Inter",
"Tottenham Hotspur",
"Everton",
"Chelsea",
"Aston Villa",
"Atlético de Madrid",
"FC Bayern München",
"Sporting CP",
"Chelsea",
"Napoli",
"Liverpool",
"Liverpool",
"Wolverhampton Wanderers",
"Arsenal",
"Leicester City",
"FC Barcelona",
"Milan",
"Sevilla FC",
"SL Benfica",
"Atlético de Madrid",
"Al Nassr",
"Manchester United",
"FC Bayern München",
"Ajax",
"SL Benfica",
"Bergamo Calcio",
"Chelsea",
"Borussia Dortmund",
"Real Sociedad",
"Borussia Dortmund",
"Valencia CF",
"Bergamo Calcio",
"Crystal Palace",
"Real Madrid",
"PFC CSKA Moscow",
"Paris Saint-Germain",
"FC Porto",
"Manchester United",
"Aston Villa",
"Shanghai Port FC",
"Borussia Mönchengladbach",
"Athletic Club",
"LAFC",
"FC Porto",
"Salernitana",
"Tottenham Hotspur",
"Sevilla FC",
"Medipol Başakşehir",
"Villarreal CF",
"Everton",
"Venezia",
"Trabzonspor",
"FC Barcelona",
"Atlético de Madrid",
"Juventus",
"Bayer 04 Leverkusen",
"Tottenham Hotspur",
"Bayer 04 Leverkusen",
"Chelsea",
"Latium",
"Olympique Lyonnais",
"Valencia CF",
"Olympique Lyonnais",
"RB Leipzig",
"Roma FC",
"Tottenham Hotspur",
"RB Leipzig",
"Arsenal",
"RB Leipzig",
"Valencia CF",
"Napoli",
"Everton",
"Manchester United",
"Levante UD",
"Napoli",
"Athletic Club",
"Inter",
"Borussia Dortmund",
"Manchester United",
"Granada CF",
"Napoli",
"Juventus",
"Manchester United",
"Real Madrid",
"RB Leipzig",
"Paris Saint-Germain",
"VfL Wolfsburg",
"Medipol Başakşehir",
"Roma FC",
"Tottenham Hotspur",
"Real Madrid",
"Villarreal CF",
"Everton",
"UD Las Palmas",
"SL Benfica",
"RB Leipzig",
"OGC Nice",
"Sevilla FC",
"LOSC Lille",
"Shakhtar Donetsk",
"Inter",
"Inter",
"SL Benfica",
"Inter Miami CF",
"Atlético de Madrid",
"Orlando City Soccer Club",
"Villarreal CF",
"Juventus",
"Liverpool",
"Olympique de Marseille",
"Real Sociedad",
"Al Nassr",
"Arsenal",
"West Ham United",
"Liverpool",
"VfL Wolfsburg",
"Real Madrid",
"Manchester United",
"Olympique de Marseille",
"Ajax",
"VfL Wolfsburg",
"Napoli",
"Leicester City",
"Borussia Dortmund",
"LOSC Lille",
"Olympique de Marseille",
"Borussia Mönchengladbach",
"Borussia Dortmund",
"Wolverhampton Wanderers",
"Manchester City",
"Arsenal",
"LOSC Lille",
"Fiorentina",
"Cruz Azul",
"SL Benfica",
"RB Leipzig",
"Olympique Lyonnais",
"Bergamo Calcio",
"RCD Espanyol de Barcelona",
"Napoli",
"Athletic Club",
"PSV",
"Spartak Moscow",
"Atlanta United",
"Ajax",
"Olympiacos CFP",
"Paris Saint-Germain",
"Paris Saint-Germain",
"Shakhtar Donetsk",
"Bayer 04 Leverkusen",
"Beijing Guoan FC",
"Seattle Sounders FC",
"Udinese",
"Villarreal CF",
"Royal Antwerp FC",
"Real Madrid",
"Trabzonspor",
"Shakhtar Donetsk",
"Newcastle United",
"Fiorentina",
"Ajax",
"Borussia Dortmund",
"Olympique Lyonnais",
"VfL Wolfsburg",
"Real Madrid",
"Atlético de Madrid",
"Ajax",
"Ajax",
"AZ",
"SL Benfica",
"LOSC Lille",
"Milan",
"CA Osasuna",
"AS Monaco",
"Manchester United",
"Latium",
"Borussia Mönchengladbach",
"Tottenham Hotspur",
"RC Celta",
"Milan",
"Stade Rennais FC",
"Newcastle United",
"FC Porto",
"VfL Wolfsburg",
"Shenzhen FC",
"Sport-Club Freiburg",
"Everton",
"Seattle Sounders FC",
"Al Hilal",
"Udinese",
"Atlético de Madrid",
"Real Betis",
"Liverpool",
"Leeds United",
"Newcastle United",
"Roma FC",
"West Ham United",
"Inter Miami CF",
"Rayo Vallecano",
"FC Barcelona",
"FC Barcelona",
"Latium",
"Tottenham Hotspur",
"Inter",
"Bayer 04 Leverkusen",
"Paris Saint-Germain",
"Real Madrid",
"Manchester United",
"Ajax",
"AS Monaco",
"RCD Espanyol de Barcelona",
"Sporting CP",
"LOSC Lille",
"PSV",
"Granada CF",
"Trabzonspor",
"Roma FC",
"Liverpool",
"Latium",
"Watford",
"Milan",
"Sevilla FC",
"Aston Villa",
"Juventus",
"AS Monaco",
"Wolverhampton Wanderers",
"Paris Saint-Germain",
"Olympique Lyonnais",
"Aston Villa",
"Real Betis",
"RC Lens",
"Wolverhampton Wanderers",
"Olympique Lyonnais",
"Spartak Moscow",
"SK Slavia Praha",
"Montpellier Hérault SC",
"Manchester City",
"Club Brugge KV",
"Latium",
"Beşiktaş JK",
"Chelsea",
"Adana Demirspor",
"Hertha Berlin",
"Bologna",
"Tigres de la UANL",
"Crystal Palace",
"Watford",
"Genoa",
"AFC Bournemouth",
"FC Porto",
"Çaykur Rizespor",
"RC Celta",
"Watford",
"PSV",
"SK Slavia Praha",
"SK Slavia Praha",
"SK Slavia Praha",
"Stade Rennais FC",
"Granada CF",
"Ajax",
"Leicester City",
"Milan",
"SC Braga",
"RC Lens",
"FC Porto",
"Juventus",
"Olympiacos CFP",
"RB Leipzig",
"Olympique de Marseille",
"OGC Nice",
"PSV",
"Bergamo Calcio",
"SL Benfica",
"RB Leipzig",
"KRC Genk",
"Portimonense SC",
"Leeds United",
"Newcastle United",
"Cagliari",
"Club Brugge KV",
"Spartak Moscow",
"Eintracht Frankfurt",
"Al Hilal",
"Cruz Azul",
"Dinamo Zagreb",
"OGC Nice",
"TSG Hoffenheim",
"Shenzhen FC",
"Trabzonspor",
"Al Ittihad",
"VfL Wolfsburg",
"Borussia Dortmund",
"Beşiktaş JK",
"Perth Glory",
"FC Cartagena",
"Hertha Berlin",
"Göztepe SK",
"Club Tijuana",
"FC Barcelona",
"FC Barcelona",
"FC Porto",
"Viktoria Plzeň",
"OGC Nice",
"AS Monaco",
"OGC Nice",
"UD Almería",
"Club América",
"Napoli",
"1. FSV Mainz 05",
"Al Nassr",
"1. FSV Mainz 05",
"Dalian Professional Football Club",
"Fiorentina",
"Cagliari",
"Levante UD",
"SD Huesca",
"Hertha Berlin",
"PSV",
"VfB Stuttgart",
"Al Hilal",
"Venezia",
"Vitesse",
"VfL Wolfsburg",
"West Ham United",
"Al Ittihad",
"Bologna",
"Beşiktaş JK",
"SD Huesca",
"Club Atlético Platense",
"Estudiantes de La Plata",
"Club Atlético Sarmiento",
"Ajax",
"RB Leipzig",
"RCD Espanyol de Barcelona",
"VfB Stuttgart",
"Brentford",
"RCD Mallorca",
"RC Lens",
"Olympiacos CFP",
"Feyenoord",
"Seattle Sounders FC",
"Daegu FC",
"New York Red Bulls",
"FC Cincinnati",
"Beşiktaş JK",
"FC Nantes",
"Portland Timbers",
"AFC Bournemouth",
"AFC Bournemouth",
"1. FSV Mainz 05",
"Celtic",
"Al Hilal",
"Austin FC",
"Portland Timbers",
"Fútbol Club Juárez",
"F.C. København",
"Ajax",
"RCD Mallorca",
"Macarthur FC",
"Royal Antwerp FC",
"Rayo Vallecano",
"Burnley",
"Inter",
"FC Barcelona",
"Beşiktaş JK",
"Sevilla FC",
"Borussia Mönchengladbach",
"West Ham United",
"Juventus",
"Sassuolo",
"Milan",
"Inter",
"Paris Saint-Germain",
"Sevilla FC",
"Levante UD",
"Arsenal",
"PSV",
"Ajax",
"Al Shabab",
"Sevilla FC",
"Villarreal CF",
"VfL Wolfsburg",
"Sporting CP",
"Brighton & Hove Albion",
"Leicester City",
"Bergamo Calcio",
"Athletic Club",
"Leeds United",
"Getafe CF",
"FC Porto",
"Torino",
"Real Sociedad",
"Southampton",
"Olympique de Marseille",
"RB Leipzig",
"Athletic Club",
"West Ham United",
"Milan",
"Burnley",
"Paris Saint-Germain",
"Ajax",
"FC Barcelona",
"Juventus",
"Aston Villa",
"SL Benfica",
"Bologna",
"1. FC Union Berlin",
"VavaCars Fatih Karagümrük SK",
"Latium",
"LOSC Lille",
"Tigres de la UANL",
"LOSC Lille",
"Real Betis",
"Granada CF",
"Watford",
"Sampdoria",
"Everton",
"Roma FC",
"Rangers FC",
"Atlético de Madrid",
"West Ham United",
"Dynamo Kyiv",
"Sporting CP",
"Athletic Club",
"Valencia CF",
"Inter",
"Inter",
"Roma FC",
"Milan",
"Tottenham Hotspur",
"Athletic Club",
"Sevilla FC",
"Real Betis",
"Borussia Mönchengladbach",
"Manchester United",
"Liverpool",
"FC Bayern München",
"Chelsea",
"SL Benfica",
"Tottenham Hotspur",
"Wolverhampton Wanderers",
"Stade Rennais FC",
"Levante UD",
"Everton",
"Sporting CP",
"Montpellier Hérault SC",
"FC Barcelona",
"Tigres de la UANL",
"PSV",
"Toronto FC",
"Atlético de Madrid",
"Napoli",
"Bergamo Calcio",
"Eintracht Frankfurt",
"Villarreal CF",
"Cagliari",
"Sporting CP",
"Real Betis",
"FC Porto",
"Bergamo Calcio",
"Juventus",
"Fiorentina",
"Inter",
"West Ham United",
"Cagliari",
"Real Sociedad",
"Olympique de Marseille",
"Fenerbahçe SK",
"Valencia CF",
"Athletic Club",
"Leicester City",
"Wolverhampton Wanderers",
"Vissel Kobe",
"Cádiz CF",
"Galatasaray SK",
"Newcastle United",
"Colón de Santa Fe",
"LOSC Lille",
"Tottenham Hotspur",
"FC Porto",
"AS Monaco",
"Bergamo Calcio",
"Getafe CF",
"Villarreal CF",
"Levante UD",
"Juventus",
"Feyenoord",
"Brighton & Hove Albion",
"Bayer 04 Leverkusen",
"Fiorentina",
"Real Sociedad",
"Eintracht Frankfurt",
"Getafe CF",
"Arsenal",
"Real Madrid",
"OGC Nice",
"Borussia Mönchengladbach",
"FC Bayern München",
"West Ham United",
"Real Sociedad",
"Aston Villa",
"LOSC Lille",
"Borussia Mönchengladbach",
"AS Monaco",
"Getafe CF",
"Leicester City",
"SL Benfica",
"Everton",
"Sevilla FC",
"Borussia Dortmund",
"Sporting CP",
"Bergamo Calcio",
"Torino",
"SC Braga",
"Juventus",
"KRC Genk",
"Sport-Club Freiburg",
"Bayer 04 Leverkusen",
"Villarreal CF",
"CA Osasuna",
"FC Porto",
"Beşiktaş JK",
"Borussia Mönchengladbach",
"RCD Espanyol de Barcelona",
"Bergamo Calcio",
"Manchester United",
"Villarreal CF",
"Borussia Mönchengladbach",
"Shakhtar Donetsk",
"Tottenham Hotspur",
"Manchester City",
"Granada CF",
"Borussia Mönchengladbach",
"Ajax",
"Olympique de Marseille",
"Bayer 04 Leverkusen",
"Wolverhampton Wanderers",
"RCD Espanyol de Barcelona",
"Tottenham Hotspur",
"Wolverhampton Wanderers",
"Arsenal",
"Elche CF",
"Inter",
"Granada CF",
"Olympiacos CFP",
"Olympique Lyonnais",
"Sevilla FC",
"Gimnasia y Esgrima La Plata",
"Villarreal CF",
"Chelsea",
"Guangzhou FC",
"Burnley",
"Guangzhou FC",
"Paris Saint-Germain",
"Manchester United",
"Real Sociedad",
"FC Barcelona",
"Burnley",
"West Ham United",
"Villarreal CF",
"Tigres de la UANL",
"Olympiacos CFP",
"Granada CF",
"Everton",
"Milan",
"Sampdoria",
"Guangzhou City",
"Al Hilal",
"Liverpool",
"Cerezo Osaka",
"Levante UD",
"Juventus",
"Venezia",
"Atlético de Madrid",
"PFC CSKA Moscow",
"R. Sporting",
"Elche CF",
"FC Girondins de Bordeaux",
"Ettifaq FC",
"Borussia Mönchengladbach",
"Leicester City",
"Granada CF",
"Olympique Lyonnais",
"Fiorentina",
"Valencia CF",
"Levante UD",
"Shakhtar Donetsk",
"TSG Hoffenheim",
"Leeds United",
"OGC Nice",
"BSC Young Boys",
"Leicester City",
"Bergamo Calcio",
"Club Brugge KV",
"Wolverhampton Wanderers",
"Borussia Dortmund",
"RB Leipzig",
"Hellas Verona",
"LOSC Lille",
"Granada CF",
"RCD Espanyol de Barcelona",
"Real Sociedad",
"VfB Stuttgart",
"Leeds United",
"LOSC Lille",
"Roma FC",
"Milan",
"TSG Hoffenheim",
"Sporting CP",
"Aston Villa",
"Angers SCO",
"Leicester City",
"Real Betis",
"CA Osasuna",
"Olympique de Marseille",
"West Ham United",
"Bergamo Calcio",
"Club León",
"Latium",
"Roma FC",
"1. FC Union Berlin",
"R. Valladolid CF",
"Eintracht Frankfurt",
"Inter",
"Stade Rennais FC",
"RC Strasbourg Alsace",
"Spartak Moscow",
"SC Braga",
"Olympique Lyonnais",
"Athletic Club",
"Leicester City",
"Bayer 04 Leverkusen",
"Stade Rennais FC",
"Bergamo Calcio",
"Granada CF",
"Bayer 04 Leverkusen",
"Aston Villa",
"Sporting CP",
"Olympique Lyonnais",
"Aston Villa",
"Olympique Lyonnais",
"RB Leipzig",
"VfL Wolfsburg",
"1. FC Köln",
"Wolverhampton Wanderers",
"Roma FC",
"Real Betis",
"CA Osasuna",
"Villarreal CF",
"Leeds United",
"Eintracht Frankfurt",
"RC Celta",
"Napoli",
"VfL Wolfsburg",
"Getafe CF",
"Real Betis",
"TSG Hoffenheim",
"Leicester City",
"Tottenham Hotspur",
"AS Monaco",
"Club Brugge KV",
"Brighton & Hove Albion",
"Getafe CF",
"Torino",
"Southampton",
"AZ",
"FC Girondins de Bordeaux",
"D. Alavés",
"Real Betis",
"SL Benfica",
"RCD Mallorca",
"CA Osasuna",
"Roma FC",
"Bayer 04 Leverkusen",
"Latium",
"Burnley",
"Fiorentina",
"Sampdoria",
"CA Osasuna",
"Roma FC",
"RC Lens",
"Inter",
"Inter",
"Olympique Lyonnais",
"Everton",
"Club Brugge KV",
"LA Galaxy",
"Villarreal CF",
"Manchester United",
"Hellas Verona",
"RCD Mallorca",
"CF Fuenlabrada",
"Hertha Berlin",
"Torino",
"Spartak Moscow",
"Real Betis",
"Sevilla FC",
"FC Girondins de Bordeaux",
"Sampdoria",
"Aston Villa",
"Cádiz CF",
"Fortuna Sittard",
"SpVgg Greuther Fürth",
"RCD Espanyol de Barcelona",
"SD Ponferradina",
"Granada CF",
"Tigres de la UANL",
"Genoa",
"Bergamo Calcio",
"Newcastle United",
"FC Porto",
"FC Girondins de Bordeaux",
"Club América",
"OGC Nice",
"PSV",
"CF Monterrey",
"Al Fateh",
"D. Alavés",
"Al Ittihad",
"FC Barcelona",
"sc Heerenveen",
"SC Braga",
"R. Valladolid CF",
"Roma FC",
"Villarreal CF",
"Villarreal CF",
"Borussia Dortmund",
"FC Barcelona",
"AS Monaco",
"PSV",
"Napoli",
"VfB Stuttgart",
"Burnley",
'"Cruz" Azul',
"Milan",
"Sampdoria",
"Real Sociedad",
"Chelsea",
"SL Benfica",
"Fiorentina",
"Santos Laguna",
"VfB Stuttgart",
"FC Porto",
"Bergamo Calcio",
"Feyenoord",
"Aytemiz Alanyaspor",
"Stade Rennais FC",
"LOSC Lille",
"OGC Nice",
"Leeds United",
"Aston Villa",
"Eintracht Frankfurt",
"FC Bayern München",
"Olympique de Marseille",
"Ajax",
"Crystal Palace",
"Cádiz CF",
"Beşiktaş JK",
"Galatasaray SK",
"Atlanta United",
"Toronto FC",
"AS Monaco",
"FC Augsburg",
"West Ham United",
"Sevilla FC",
"Leicester City",
"Bayer 04 Leverkusen",
"Southampton",
"FC Nantes",
"Leicester City",
"Olympique Lyonnais",
"FC Metz",
"AS Monaco",
"Norwich City",
"Al Hilal",
"Villarreal CF",
"Arsenal",
"Southampton",
"Levante UD",
"Olympiacos CFP",
"D. Alavés",
"Dynamo Kyiv",
"Everton",
"Bayer 04 Leverkusen",
"1. FC Köln",
"Everton",
"Fiorentina",
"Sassuolo",
"SC Braga",
"Spartak Moscow",
"Crystal Palace",
"Olympique de Marseille",
"Al Nassr",
"Nîmes Olympique",
"Real Madrid",
"Tottenham Hotspur",
"Rayo Vallecano",
"Borussia Mönchengladbach",
"West Ham United",
"Latium",
"Club Universidad Nacional",
"Real Sociedad",
"VfL Wolfsburg",
"Olympique de Marseille",
"Latium",
"AS Monaco",
"Aston Villa",
"KRC Genk",
"Bergamo Calcio",
"Olympiacos CFP",
"VfL Wolfsburg",
"Napoli",
"Stade Rennais FC",
"Elche CF",
"CF Monterrey",
"Everton",
"Al Hilal",
"Al Nassr",
"Everton",
"Arsenal",
"RC Celta",
"Leeds United",
"Wolverhampton Wanderers",
"West Ham United",
"VfL Wolfsburg",
"Inter",
"Brighton & Hove Albion",
"Everton",
"Juventus",
"SL Benfica",
"New England Revolution",
"Latium",
"Milan",
"Sevilla FC",
"Trabzonspor",
"Brighton & Hove Albion",
"Aston Villa",
"RB Leipzig",
"Granada CF",
"Brighton & Hove Albion",
"Stade de Reims",
"Levante UD",
"Sporting CP",
"SK Slavia Praha",
"Lokomotiv Moscow",
"Newcastle United",
"Valencia CF",
"Sassuolo",
"Borussia Dortmund",
"Southampton",
"RCD Espanyol de Barcelona",
"Napoli",
"RC Celta",
"Lokomotiv Moscow",
"Medipol Başakşehir",
"Eintracht Frankfurt",
"Rangers FC",
"Al Nassr",
"CF Monterrey",
"CF Monterrey",
"VfL Wolfsburg",
"D. Alavés",
"FC Augsburg",
"Shanghai Shenhua",
"Rangers FC",
"Hellas Verona",
"Real Betis",
"Shanghai Port FC",
"Everton",
"West Ham United",
"RC Celta",
"SL Benfica",
"Real Betis",
"FC Barcelona",
"1. FC Union Berlin",
"RCD Espanyol de Barcelona",
"Watford",
"Portland Timbers",
"CA Osasuna",
"Athletic Club",
"CA Osasuna",
"CA Osasuna",
"Everton",
"Club Brugge KV",
"West Ham United",
"Guangzhou FC",
"SV Werder Bremen",
"Fenerbahçe SK",
"Shenzhen FC",
"Club León",
"Elche CF",
"Granada CF",
"Demir Grup Sivasspor",
"Hertha Berlin",
"Eintracht Frankfurt",
"SK Slavia Praha",
"Olympique Lyonnais",
"SL Benfica",
"Olympiacos CFP",
"RC Strasbourg Alsace",
"D. Alavés",
"FC Porto",
"CF Monterrey",
"Olympiacos CFP",
"Portland Timbers",
"LA Galaxy",
"Latium",
"VavaCars Fatih Karagümrük SK",
"Granada CF",
"Levante UD",
"Vitória SC",
"Levante UD",
"UD Almería",
"Cagliari",
"Fiorentina",
"Valencia CF",
"Sporting CP",
"Fenerbahçe SK",
"Sporting CP",
"Cagliari",
"Getafe CF",
"Udinese",
"FC Porto",
"Getafe CF",
"Cádiz CF",
"Getafe CF",
"Fiorentina",
"Everton",
"Everton",
"Tigres de la UANL",
"Club Deportivo Guadalajara",
"Aston Villa",
"Sampdoria",
"Urawa Red Diamonds",
"FC Girondins de Bordeaux",
"LAFC",
"Fenerbahçe SK",
"Fenerbahçe SK",
"Panathinaikos FC",
"VavaCars Fatih Karagümrük SK",
"Sporting CP",
"Roma FC",
"Sporting CP",
"SL Benfica",
"Arsenal",
"Shakhtar Donetsk",
"Shakhtar Donetsk",
"Tottenham Hotspur",
"Olympiacos CFP",
"Sparta Praha",
"FC Basel 1893",
"OGC Nice",
"FC Porto",
"Southampton",
"Wolverhampton Wanderers",
"Stade Rennais FC",
"Roma FC",
"Dynamo Kyiv",
"Dynamo Kyiv",
"Dynamo Kyiv",
"Stade Rennais FC",
"SK Slavia Praha",
"FC Barcelona",
"Milan",
"VfL Wolfsburg",
"AS Monaco",
"FC Paços de Ferreira",
"Bologna",
"RCD Espanyol de Barcelona",
"Club América",
"Olympique de Marseille",
"Paris Saint-Germain",
"Feyenoord",
"Real Betis",
"Getafe CF",
"Real Sociedad",
"Arsenal",
"Norwich City",
"Torino",
"AS Monaco",
"Fiorentina",
"KRC Genk",
"RCD Espanyol de Barcelona",
"Cruz Azul",
"RCD Espanyol de Barcelona",
"Villarreal CF",
"Club América",
"CA Osasuna",
"RC Celta",
"Olympique de Marseille",
"Vitória SC",
"TSG Hoffenheim",
"Bologna",
"FC Porto",
"Torino",
"Manchester United",
"Minnesota United FC",
"Sport-Club Freiburg",
"VfB Stuttgart",
"Eintracht Frankfurt",
"RCD Mallorca",
"Bologna",
"PSV",
"Rayo Vallecano",
"Club Brugge KV",
"Arsenal",
"VfL Wolfsburg",
"SL Benfica",
"Sport-Club Freiburg",
"Roma FC",
"Hertha Berlin",
"Norwich City",
"SD Eibar",
"R. Valladolid CF",
"Club León",
"Adana Demirspor",
"Sevilla FC",
"Fiorentina",
"Roma FC",
"RB Leipzig",
"Olympiacos CFP",
"Sheffield United",
"Chicago Fire Football Club",
"Hertha Berlin",
"RC Strasbourg Alsace",
"Trabzonspor",
"Inter",
"Paris Saint-Germain",
"Southampton",
"AS Saint-Étienne",
"PSV",
"Montpellier Hérault SC",
"Fenerbahçe SK",
"CD Leganés",
"SK Slavia Praha",
"Rangers FC",
"Seattle Sounders FC",
"Club América",
"Al Ahli",
"Milan",
"Watford",
"Hertha Berlin",
"FC Girondins de Bordeaux",
"Vitória SC",
"Norwich City",
"Lokomotiv Moscow",
"Southampton",
"Rangers FC",
"Levante UD",
"PAOK",
"Burnley",
"Southampton",
"Venezia",
"AFC Bournemouth",
"Olympique Lyonnais",
"Real Sociedad",
"Aston Villa",
"Dinamo Zagreb",
"Napoli",
"Dinamo Zagreb",
"Columbus Crew",
"Club Atlas",
"Tigres de la UANL",
"Stade Rennais FC",
"Liverpool",
"Olympiacos CFP",
"Sevilla FC",
"Sheffield United",
"Vitesse",
"FC Girondins de Bordeaux",
"Urawa Red Diamonds",
"Bayer 04 Leverkusen",
"Melbourne City",
"Brentford",
"RC Strasbourg Alsace",
"Club Brugge KV",
"Hellas Verona",
"Guangzhou FC",
"Aston Villa",
"SC Braga",
"FC Metz",
"Newcastle United",
"Santos Laguna",
"Sparta Praha",
"RC Strasbourg Alsace",
"R. Valladolid CF",
"Stade de Reims",
"TSG Hoffenheim",
"AEK Athens",
"SL Benfica",
"Fenerbahçe SK",
"Tigres de la UANL",
"Arsenal",
"Crystal Palace",
"Montpellier Hérault SC",
"Crystal Palace",
"Valencia CF",
"Newcastle United",
"Juventus",
"Villarreal CF",
"SV Werder Bremen",
"Torino",
"SL Benfica",
"RC Celta",
"Demir Grup Sivasspor",
"Burnley",
"Orlando City Soccer Club",
"Beşiktaş JK",
"R. Valladolid CF",
"Olympiacos CFP",
"Stade Rennais FC",
"FC Metz",
"1. FC Union Berlin",
"Torino",
"Eintracht Frankfurt",
"FC Augsburg",
"Sport-Club Freiburg",
"FC Schalke 04",
"Paris Saint-Germain",
"Fiorentina",
"Hertha Berlin",
"Genoa",
"Arsenal",
"Montpellier Hérault SC",
"Feyenoord",
"PSV",
"FC Midtjylland",
"Burnley",
"RCD Espanyol de Barcelona",
"RC Celta",
"FC Nantes",
"Southampton",
"Pachuca",
"D. Alavés",
"Feyenoord",
"AS Saint-Étienne",
"West Ham United",
"Sassuolo",
"ESTAC Troyes",
"Torino",
"Granada CF",
"TSG Hoffenheim",
"RC Celta",
"Club Brugge KV",
"Brighton & Hove Albion",
"Norwich City",
"Cagliari",
"TSG Hoffenheim",
"UD Almería",
"New England Revolution",
"PFC CSKA Moscow",
"Lokomotiv Moscow",
"Adana Demirspor",
"Girona FC",
"VavaCars Fatih Karagümrük SK",
"Galatasaray SK",
"Leeds United",
"Galatasaray SK",
"Sampdoria",
"Angers SCO",
"FC Bayern München",
"Leicester City",
"Sampdoria",
"FC Red Bull Salzburg",
"Genoa",
"Trabzonspor",
"Bologna",
"Burnley",
"Leicester City",
"F.C. København",
"Southampton",
"Western United FC",
"AS Monaco",
"OGC Nice",
"Galatasaray SK",
"Deportivo Toluca",
"Servette FC",
"Rangers FC",
"Fenerbahçe SK",
"Beşiktaş JK",
"Empoli",
"Olympique Lyonnais",
"Newcastle United",
"Hajduk Split",
"Granada CF",
"Ajax",
"D. Alavés",
"Club Deportivo Guadalajara",
"Al Taawoun",
"Bologna",
"Cruz Azul",
"Medipol Başakşehir",
"AFC Bournemouth",
"RCD Mallorca",
"Medipol Başakşehir",
"Galatasaray SK",
"FC St. Gallen 1879",
"Al Shabab",
"Aston Villa",
"Empoli",
"Al Ittihad",
"Salernitana",
"CD Leganés",
"Al Hilal",
"Salernitana",
"Salernitana",
"Olympique de Marseille",
"Lokomotiv Moscow",
"Sampdoria",
"Getafe CF",
"FC Metz",
"Gallos Blancos de Querétaro",
"Pachuca",
"Cruz Azul",
"Roma FC",
"CF Monterrey",
"Olympiacos CFP",
"FC Red Bull Salzburg",
"FC Schalke 04",
"Parma",
"Al Ittihad",
"Fenerbahçe SK",
"Udinese",
"Fenerbahçe SK",
"Olympique de Marseille",
"VavaCars Fatih Karagümrük SK",
"Medipol Başakşehir",
"Ferencvárosi TC",
"FC Barcelona",
"SK Slavia Praha",
"FC Bayern München",
"Stade Rennais FC",
"Shakhtar Donetsk",
"SK Slavia Praha",
"Galatasaray SK",
"Fenerbahçe SK",
"OGC Nice",
"Sporting CP",
"Valencia CF",
"LOSC Lille",
"Club Brugge KV",
"FC Augsburg",
"CA Osasuna",
"Athletic Club",
"Sparta Praha",
"West Ham United",
"Sampdoria",
"DSC Arminia Bielefeld",
"SC Braga",
"Roma FC",
"Udinese",
"RB Leipzig",
"Olympique de Marseille",
"SL Benfica",
"AS Saint-Étienne",
"FC Girondins de Bordeaux",
"Norwich City",
"Feyenoord",
"Brighton & Hove Albion",
"Watford",
"RC Lens",
"Stade Brestois 29",
"Hellas Verona",
"SL Benfica",
"D. Alavés",
"Valencia CF",
"Rangers FC",
"UD Almería",
"Tottenham Hotspur",
"Roma FC",
"RCD Espanyol de Barcelona",
"Lokomotiv Moscow",
"Norwich City",
"Brighton & Hove Albion",
"Genoa",
"Getafe CF",
"Sevilla FC",
"Sporting CP",
"FC Augsburg",
"Borussia Dortmund",
"CA Osasuna",
"ESTAC Troyes",
"RSC Anderlecht",
"Bologna",
"AS Saint-Étienne",
"Galatasaray SK",
"Newcastle United",
"Villarreal CF",
"Watford",
"Spartak Moscow",
"BSC Young Boys",
"FC Metz",
"Torino",
"Crystal Palace",
"LAFC",
"FC Girondins de Bordeaux",
"RC Celta",
"Stade de Reims",
"FC Metz",
"CF Monterrey",
"OGC Nice",
"Lech Poznań",
"BSC Young Boys",
"Brentford",
"Granada CF",
"Granada CF",
"Crystal Palace",
"FC Red Bull Salzburg",
"Colón de Santa Fe",
"Arsenal",
"Damac FC",
"R. Valladolid CF",
"FC Porto",
"AZ",
"Middlesbrough",
"UD Almería",
"RC Celta",
"Spartak Moscow",
"Cádiz CF",
"FC Augsburg",
"Philadelphia Union",
"CF Monterrey",
"Santos Laguna",
"Sporting CP",
"Everton",
"CF Monterrey",
"Go Ahead Eagles",
"Milan",
"KRC Genk",
"Cádiz CF",
"Torino",
"VfB Stuttgart",
"SL Benfica",
"AEK Athens",
"Pachuca",
"AS Saint-Étienne",
"Lokomotiv Moscow",
"Olympique Lyonnais",
"Adana Demirspor",
"Al Batin",
"Beşiktaş JK",
"Liverpool",
"CF Monterrey",
"FC Nantes",
"Wolverhampton Wanderers",
"Al Taawoun",
"Sport-Club Freiburg",
"Aston Villa",
"CF Monterrey",
"Arsenal",
"Norwich City",
"R. Valladolid CF",
"Lokomotiv Moscow",
"Genoa",
"Torino",
"Vitória SC",
"RC Strasbourg Alsace",
"Real Madrid",
"Burnley",
"Levante UD",
"Estudiantes de La Plata",
"Stade Brestois 29",
"Borussia Dortmund",
"AFC Bournemouth",
"Brentford",
"Lokomotiv Moscow",
"Sassuolo",
"Olympiacos CFP",
"Latium",
"TSG Hoffenheim",
"Montpellier Hérault SC",
"Getafe CF",
"RC Celta",
"Aston Villa",
"Nîmes Olympique",
"1. FC Köln",
"Stade de Reims",
"1. FSV Mainz 05",
"Real Madrid",
"RCD Espanyol de Barcelona",
"R. Sporting",
"PAOK",
"RCD Mallorca",
"RC Lens",
"Crystal Palace",
"Austin FC",
"Levante UD",
"Real Sociedad",
"Dynamo Kyiv",
"RC Strasbourg Alsace",
"Fulham",
"Everton",
"Fenerbahçe SK",
"Al Shabab",
"RCD Mallorca",
"Stade Rennais FC",
"CF Monterrey",
"Marítimo",
"Cruz Azul",
"Hellas Verona",
"Beşiktaş JK",
"RSC Anderlecht",
"CF Monterrey",
"FC Porto",
"Eintracht Frankfurt",
"Rayo Vallecano",
"Bayer 04 Leverkusen",
"VfL Bochum 1848",
"Fulham",
"1. FSV Mainz 05",
"Burnley",
"Fulham",
"Medipol Başakşehir",
"TSG Hoffenheim",
"Nottingham Forest",
"Elche CF",
"Colón de Santa Fe",
"Levante UD",
"Club León",
"Club Brugge KV",
"FC Porto",
"Club Brugge KV",
"Chelsea",
"Rangers FC",
"Fiorentina",
"Hellas Verona",
"FC Lorient",
"Hellas Verona",
"OGC Nice",
"Brøndby IF",
"FC Augsburg",
"FC Augsburg",
"D. Alavés",
"Sevilla FC",
"Columbus Crew",
"Inter Miami CF",
"Al Ittihad",
"Aston Villa",
"FC Basel 1893",
"Dynamo Kyiv",
"Dalian Professional Football Club",
"Angers SCO",
"ESTAC Troyes",
"Rayo Vallecano",
"Vancouver Whitecaps FC",
"Celtic",
"Urawa Red Diamonds",
"Arsenal",
"Tigres de la UANL",
"Newcastle United",
"Sassuolo",
"Wolverhampton Wanderers",
"Brighton & Hove Albion",
"Parma",
"Al Hilal",
"Brighton & Hove Albion",
"RSC Anderlecht",
"Fenerbahçe SK",
"Arsenal",
"Dinamo Zagreb",
"Seattle Sounders FC",
"Hajduk Split",
"Cagliari",
"Sampdoria",
"1. FSV Mainz 05",
"Fenerbahçe SK",
"Latium",
"Ettifaq FC",
"Sheffield United",
"CF Monterrey",
"PAOK",
"FC Bayern München",
"Hellas Verona",
"Angers SCO",
"Leeds United",
"Southampton",
"SV Werder Bremen",
"SC Braga",
"Hellas Verona",
"Newcastle United",
"Valencia CF",
"TSG Hoffenheim",
"Fiorentina",
"Crystal Palace",
"Celtic",
"SD Huesca",
"Bologna",
"1. FC Köln",
"FC Utrecht",
"Sassuolo",
"SD Eibar",
"Malmö FF",
"Vitória SC",
"Cádiz CF",
"SD Eibar",
"Norwich City",
"Leicester City",
"Sampdoria",
"RCD Mallorca",
"Girona FC",
"Brighton & Hove Albion",
"Real Betis",
"Crystal Palace",
"Torino",
"Fulham",
"1. FC Köln",
"Real Betis",
"Brentford",
"Adana Demirspor",
"PSV",
"Udinese",
"AS Saint-Étienne",
"Getafe CF",
"Medipol Başakşehir",
"GwangJu FC",
"Fiorentina",
"Club Tijuana",
"Burnley",
"Galatasaray SK",
"Crystal Palace",
"Watford",
"Athletic Club",
"AEK Athens",
"Watford",
"Cagliari",
"Leeds United",
"TSG Hoffenheim",
"Changchun Yatai FC",
"Rangers FC",
"Sheffield United",
"Newcastle United",
"Fenerbahçe SK",
"Club de Foot Montréal",
"Sparta Praha",
"Burnley",
"R. Valladolid CF",
"Club León",
"Aytemiz Alanyaspor",
"Lokomotiv Moscow",
"Hellas Verona",
"Watford",
"Al Shabab",
"Fraport TAV Antalyaspor",
"Sporting Kansas City",
"Panathinaikos FC",
"Angers SCO",
"Moreirense FC",
"Qingdao FC",
"Crystal Palace",
"New York City FC",
"FC Schalke 04",
"Sport-Club Freiburg",
"Everton",
"Al Ahli",
"Montpellier Hérault SC",
"Newcastle United",
"Sparta Praha",
"Brighton & Hove Albion",
"Orlando City Soccer Club",
"Roma FC",
"Çaykur Rizespor",
"FC Paços de Ferreira",
"Henan Songshan Longmen FC",
"PAOK",
"OGC Nice",
"BSC Young Boys",
"Shandong Taishan",
"IFK Göteborg",
"R. Sporting",
"KAA Gent",
"Crystal Palace",
"Crystal Palace",
"Watford",
"Pachuca",
"RSC Anderlecht",
"Valenciennes FC",
"RCD Mallorca",
"Vissel Kobe",
"Molde FK",
"West Ham United",
"Sassuolo",
"Athletic Club",
"Atlético de Madrid",
"FC Barcelona",
"FC Bayern München",
"Paris Saint-Germain",
"Liverpool",
"Manchester City",
"Real Madrid",
"Paris Saint-Germain",
"Piemonte Calcio",
"Tottenham Hotspur",
"VfL Wolfsburg",
"Inter",
"RB Leipzig",
"Borussia Mönchengladbach",
"Leicester City",
"Milan",
"Aston Villa",
"Manchester United",
"Ajax",
"Chelsea",
"Everton",
"Burnley",
"Arsenal",
"Bayer 04 Leverkusen",
"Villarreal CF",
"Dinamo Zagreb",
"Athletic Club",
"Olympique Lyonnais",
"FC Barcelona",
"West Ham United",
"Eintracht Frankfurt",
"Roma FC",
"Genoa",
"West Ham United",
"Real Sociedad",
"SL Benfica",
"Real Betis",
"Cagliari",
"Olympiacos CFP",
"Levante UD",
"Galatasaray SK",
"Venezia",
"Olympique de Marseille",
"Latium",
"Piemonte Calcio",
"Crystal Palace",
"Borussia Dortmund",
"Club Brugge KV",
"Parma",
"Napoli",
"Milan",
"SL Benfica",
"DSC Arminia Bielefeld",
"Tottenham Hotspur",
"Sevilla FC",
"TSG Hoffenheim",
"Getafe CF",
"Newcastle United",
"Bergamo Calcio",
"FC Porto",
"Valencia CF",
"Sporting CP",
"Olympique de Marseille",
"Sassuolo",
"SV Werder Bremen",
"Manchester United",
"Sevilla FC",
"Villarreal CF",
"OGC Nice",
"D. Alavés",
"CF Monterrey",
"PFC CSKA Moscow",
"Club América",
"SK Slavia Praha",
"Borussia Dortmund",
"Trabzonspor",
"Napoli",
"Wolverhampton Wanderers",
"SC Braga",
"Chelsea",
"Elche CF",
"Atlético de Madrid",
"FC Augsburg",
"Udinese",
"Tigres de la UANL",
"FC Girondins de Bordeaux",
"Gil Vicente FC",
"Stade de Reims",
"FC Nantes",
"Bayer 04 Leverkusen",
"Sampdoria",
"CA Osasuna",
"Borussia Dortmund",
"FC Metz",
"Real Betis",
"Watford",
"Club Universidad Nacional",
"Latium",
"R. Sporting",
"Salernitana",
"RCD Mallorca",
"AS Saint-Étienne",
"Fenerbahçe SK",
"Leeds United",
"VfB Stuttgart",
"Manchester City",
"Feyenoord",
"Angers SCO",
"Montpellier Hérault SC",
"Cádiz CF",
"Fiorentina",
"Club Atlas",
"Paris Saint-Germain",
"West Bromwich Albion",
"Fulham",
"Hertha Berlin",
"Milan",
"Stade Brestois 29",
"RC Strasbourg Alsace",
"Real Sociedad",
"Parma",
"Lokomotiv Moscow",
"Norwich City",
"RCD Espanyol de Barcelona",
"Rangers FC",
"Aston Villa",
"Granada CF",
"Sparta Praha",
"Santos Laguna",
"Stade Brestois 29",
"Brighton & Hove Albion",
"BSC Young Boys",
"Philadelphia Union",
"Bergamo Calcio",
"FC Luzern",
"Sheffield United",
"PSV",
"RSC Anderlecht",
"Stade Rennais FC",
"1. FC Köln",
"R. Valladolid CF",
"Real Betis",
"Newcastle United",
"1. FC Union Berlin",
"Beşiktaş JK",
"Torino",
"Club León",
"Colón de Santa Fe",
"Everton",
"Al Ittihad",
"Manchester United",
"SD Huesca",
"Hertha Berlin",
"Ajax",
"Dynamo Kyiv",
"Inter",
"New England Revolution",
"PSV",
"AS Monaco",
"Valencia CF",
"Mazatlán Fútbol Club",
"Ulsan Hyundai",
"Sport-Club Freiburg",
"Rayo Vallecano",
"RC Celta",
"RC Celta",
"Panathinaikos FC",
"Liverpool",
"Lecce",
"R. Sporting",
"Marítimo",
"AIK",
"Spezia",
"UD Almería",
"Bologna",
"Southampton",
"FC Bayern München",
"Southampton",
"West Ham United",
"Club Tijuana",
"Ajax",
"Cruz Azul",
"RC Lens",
"Shakhtar Donetsk"
]
