league = [
"Ligue 1 Uber Eats",
"Bundesliga",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Premier League",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Ligue 1 Uber Eats",
"Eredivisie",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"Hellas Liga",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"Bundesliga",
"Bundesliga",
"Bundesliga",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"Liga Portugal",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"MBS Pro League",
"Premier League",
"Serie A TIM",
"Bundesliga",
"MLS",
"Premier League",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Liga Portugal",
"Premier League",
"Serie A TIM",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"Liga Portugal",
"LaLiga Santander",
"MBS Pro League",
"Premier League",
"Bundesliga",
"Eredivisie",
"Liga Portugal",
"Serie A TIM",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"League of Russia",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Serie A TIM",
"LaLiga Santander",
"CSL",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Süper Lig",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Süper Lig",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Premier League",
"Bundesliga",
"Premier League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Bundesliga",
"Serie A TIM",
"Premier League",
"Bundesliga",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Ligue 1 Uber Eats",
"Bundesliga",
"Süper Lig",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"LaLiga SmartBank",
"Liga Portugal",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Ukrayina Liha",
"Serie A TIM",
"Serie A TIM",
"Liga Portugal",
"MLS",
"LaLiga Santander",
"MLS",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"MBS Pro League",
"Premier League",
"Premier League",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Ligue 1 Uber Eats",
"Eredivisie",
"Bundesliga",
"Serie A TIM",
"Premier League",
"Bundesliga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Bundesliga",
"Bundesliga",
"Premier League",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LIGA BBVA MX",
"Liga Portugal",
"Bundesliga",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"Eredivisie",
"League of Russia",
"MLS",
"Eredivisie",
"Hellas Liga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Ukrayina Liha",
"Bundesliga",
"CSL",
"MLS",
"Serie A TIM",
"LaLiga Santander",
"1A Pro League",
"LaLiga Santander",
"Süper Lig",
"Ukrayina Liha",
"Premier League",
"Serie A TIM",
"Eredivisie",
"Bundesliga",
"Ligue 1 Uber Eats",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Eredivisie",
"Eredivisie",
"Eredivisie",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Liga Portugal",
"Bundesliga",
"CSL",
"Bundesliga",
"Premier League",
"MLS",
"MBS Pro League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"Serie A TIM",
"Premier League",
"MLS",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Eredivisie",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Eredivisie",
"LaLiga Santander",
"Süper Lig",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"League of Russia",
"Česká Liga",
"Ligue 1 Uber Eats",
"Premier League",
"1A Pro League",
"Serie A TIM",
"Süper Lig",
"Premier League",
"Süper Lig",
"Bundesliga",
"Serie A TIM",
"LIGA BBVA MX",
"Premier League",
"Premier League",
"Serie A TIM",
"EFL Championship",
"Liga Portugal",
"Süper Lig",
"LaLiga Santander",
"Premier League",
"Eredivisie",
"Česká Liga",
"Česká Liga",
"Česká Liga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Eredivisie",
"Premier League",
"Serie A TIM",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Serie A TIM",
"Hellas Liga",
"Bundesliga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Eredivisie",
"Serie A TIM",
"Liga Portugal",
"Bundesliga",
"1A Pro League",
"Liga Portugal",
"Premier League",
"Premier League",
"Serie A TIM",
"1A Pro League",
"League of Russia",
"Bundesliga",
"MBS Pro League",
"LIGA BBVA MX",
"Liga Hrvatska",
"Ligue 1 Uber Eats",
"Bundesliga",
"CSL",
"Süper Lig",
"MBS Pro League",
"Bundesliga",
"Bundesliga",
"Süper Lig",
"A-League",
"LaLiga SmartBank",
"Bundesliga",
"Süper Lig",
"LIGA BBVA MX",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"Česká Liga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"LaLiga SmartBank",
"LIGA BBVA MX",
"Serie A TIM",
"Bundesliga",
"MBS Pro League",
"Bundesliga",
"CSL",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"LaLiga SmartBank",
"Bundesliga",
"Eredivisie",
"Bundesliga",
"MBS Pro League",
"Serie A TIM",
"Eredivisie",
"Bundesliga",
"Premier League",
"MBS Pro League",
"Serie A TIM",
"Süper Lig",
"LaLiga SmartBank",
"LPF",
"LPF",
"LPF",
"Eredivisie",
"Bundesliga",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Hellas Liga",
"Eredivisie",
"MLS",
"K League 1",
"MLS",
"MLS",
"Süper Lig",
"Ligue 1 Uber Eats",
"MLS",
"EFL Championship",
"EFL Championship",
"Bundesliga",
"cinch Prem",
"MBS Pro League",
"MLS",
"MLS",
"LIGA BBVA MX",
"3F Superliga",
"Eredivisie",
"LaLiga Santander",
"A-League",
"1A Pro League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Süper Lig",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Eredivisie",
"Eredivisie",
"MBS Pro League",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"Liga Portugal",
"Premier League",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Liga Portugal",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"Ligue 1 Uber Eats",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Ligue 1 Uber Eats",
"Eredivisie",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Liga Portugal",
"Serie A TIM",
"Bundesliga",
"Süper Lig",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"cinch Prem",
"LaLiga Santander",
"Premier League",
"Ukrayina Liha",
"Liga Portugal",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Premier League",
"Bundesliga",
"Premier League",
"Liga Portugal",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Liga Portugal",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LIGA BBVA MX",
"Eredivisie",
"MLS",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Liga Portugal",
"LaLiga Santander",
"Liga Portugal",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Süper Lig",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"Meiji Yasuda J1",
"LaLiga Santander",
"Süper Lig",
"Premier League",
"LPF",
"Ligue 1 Uber Eats",
"Premier League",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Eredivisie",
"Premier League",
"Bundesliga",
"Serie A TIM",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Bundesliga",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Premier League",
"Ligue 1 Uber Eats",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Liga Portugal",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Liga Portugal",
"Serie A TIM",
"Serie A TIM",
"Liga Portugal",
"Serie A TIM",
"1A Pro League",
"Bundesliga",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"Süper Lig",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Ukrayina Liha",
"Premier League",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Eredivisie",
"Ligue 1 Uber Eats",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"Hellas Liga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LPF",
"LaLiga Santander",
"Premier League",
"CSL",
"Premier League",
"CSL",
"Ligue 1 Uber Eats",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"LaLiga Santander",
"LIGA BBVA MX",
"Hellas Liga",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"CSL",
"MBS Pro League",
"Premier League",
"Meiji Yasuda J1",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"League of Russia",
"LaLiga SmartBank",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"MBS Pro League",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Ukrayina Liha",
"Bundesliga",
"Premier League",
"Ligue 1 Uber Eats",
"CSSL",
"Premier League",
"Serie A TIM",
"1A Pro League",
"Premier League",
"Bundesliga",
"Bundesliga",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"Liga Portugal",
"Premier League",
"Ligue 1 Uber Eats",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"LIGA BBVA MX",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"LaLiga SmartBank",
"Bundesliga",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"League of Russia",
"Liga Portugal",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Bundesliga",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Bundesliga",
"Bundesliga",
"Bundesliga",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"1A Pro League",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Eredivisie",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Serie A TIM",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"1A Pro League",
"MLS",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga SmartBank",
"Bundesliga",
"Serie A TIM",
"League of Russia",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Eredivisie",
"Bundesliga",
"LaLiga Santander",
"LaLiga SmartBank",
"LaLiga Santander",
"LIGA BBVA MX",
"Serie A TIM",
"Serie A TIM",
"Premier League",
"Liga Portugal",
"Ligue 1 Uber Eats",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"Eredivisie",
"LIGA BBVA MX",
"MBS Pro League",
"LaLiga Santander",
"MBS Pro League",
"LaLiga Santander",
"Eredivisie",
"Liga Portugal",
"LaLiga SmartBank",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Eredivisie",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LIGA BBVA MX",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"Premier League",
"Liga Portugal",
"Serie A TIM",
"LIGA BBVA MX",
"Bundesliga",
"Liga Portugal",
"Serie A TIM",
"Eredivisie",
"Süper Lig",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Bundesliga",
"Bundesliga",
"Ligue 1 Uber Eats",
"Eredivisie",
"Premier League",
"LaLiga Santander",
"Süper Lig",
"Süper Lig",
"MLS",
"MLS",
"Ligue 1 Uber Eats",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Premier League",
"Bundesliga",
"Premier League",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"MBS Pro League",
"LaLiga Santander",
"Premier League",
"Premier League",
"LaLiga Santander",
"Hellas Liga",
"LaLiga Santander",
"Ukrayina Liha",
"Premier League",
"Bundesliga",
"Bundesliga",
"Premier League",
"Serie A TIM",
"Serie A TIM",
"Liga Portugal",
"League of Russia",
"Premier League",
"Ligue 1 Uber Eats",
"MBS Pro League",
"Ligue 2 BKT",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Premier League",
"Serie A TIM",
"LIGA BBVA MX",
"LaLiga Santander",
"Bundesliga",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"1A Pro League",
"Serie A TIM",
"Hellas Liga",
"Bundesliga",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LIGA BBVA MX",
"Premier League",
"MBS Pro League",
"MBS Pro League",
"Premier League",
"Premier League",
"LaLiga Santander",
"Premier League",
"Premier League",
"Premier League",
"Bundesliga",
"Serie A TIM",
"Premier League",
"Premier League",
"Serie A TIM",
"Liga Portugal",
"MLS",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"Süper Lig",
"Premier League",
"Premier League",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Liga Portugal",
"Česká Liga",
"League of Russia",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga Santander",
"Serie A TIM",
"LaLiga Santander",
"League of Russia",
"Süper Lig",
"Bundesliga",
"cinch Prem",
"MBS Pro League",
"LIGA BBVA MX",
"LIGA BBVA MX",
"Bundesliga",
"LaLiga Santander",
"Bundesliga",
"CSL",
"cinch Prem",
"Serie A TIM",
"LaLiga Santander",
"CSL",
"Premier League",
"Premier League",
"LaLiga Santander",
"Liga Portugal",
"LaLiga Santander",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"MLS",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"1A Pro League",
"Premier League",
"CSL",
"Bundesliga 2",
"Süper Lig",
"CSL",
"LIGA BBVA MX",
"LaLiga Santander",
"LaLiga Santander",
"Süper Lig",
"Bundesliga",
"Bundesliga",
"Česká Liga",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Hellas Liga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Liga Portugal",
"LIGA BBVA MX",
"Hellas Liga",
"MLS",
"MLS",
"Serie A TIM",
"Süper Lig",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"LaLiga Santander",
"LaLiga SmartBank",
"Serie A TIM",
"Serie A TIM",
"LaLiga Santander",
"Liga Portugal",
"Süper Lig",
"Liga Portugal",
"Serie A TIM",
"LaLiga Santander",
"Serie A TIM",
"Liga Portugal",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Serie A TIM",
"Premier League",
"Premier League",
"LIGA BBVA MX",
"LIGA BBVA MX",
"Premier League",
"Serie A TIM",
"Meiji Yasuda J1",
"Ligue 1 Uber Eats",
"MLS",
"Süper Lig",
"Süper Lig",
"Hellas Liga",
"Süper Lig",
"Liga Portugal",
"Serie A TIM",
"Liga Portugal",
"Liga Portugal",
"Premier League",
"Ukrayina Liha",
"Ukrayina Liha",
"Premier League",
"Hellas Liga",
"Česká Liga",
"CSSL",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Ukrayina Liha",
"Ukrayina Liha",
"Ukrayina Liha",
"Ligue 1 Uber Eats",
"Česká Liga",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Serie A TIM",
"LaLiga Santander",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Eredivisie",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Premier League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Serie A TIM",
"1A Pro League",
"LaLiga Santander",
"LIGA BBVA MX",
"LaLiga Santander",
"LaLiga Santander",
"LIGA BBVA MX",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Bundesliga",
"Serie A TIM",
"Liga Portugal",
"Serie A TIM",
"Premier League",
"MLS",
"Bundesliga",
"Bundesliga",
"Bundesliga",
"LaLiga Santander",
"Serie A TIM",
"Eredivisie",
"LaLiga Santander",
"1A Pro League",
"Premier League",
"Bundesliga",
"Liga Portugal",
"Bundesliga",
"Serie A TIM",
"Bundesliga",
"Premier League",
"LaLiga SmartBank",
"LaLiga SmartBank",
"LIGA BBVA MX",
"Süper Lig",
"LaLiga Santander",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"Hellas Liga",
"EFL Championship",
"MLS",
"Bundesliga",
"Ligue 1 Uber Eats",
"Süper Lig",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Ligue 1 Uber Eats",
"Eredivisie",
"Ligue 1 Uber Eats",
"Süper Lig",
"LaLiga SmartBank",
"Česká Liga",
"cinch Prem",
"MLS",
"LIGA BBVA MX",
"MBS Pro League",
"Serie A TIM",
"Premier League",
"Bundesliga",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Premier League",
"League of Russia",
"Premier League",
"cinch Prem",
"LaLiga Santander",
"Hellas Liga",
"Premier League",
"Premier League",
"Serie A TIM",
"EFL Championship",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"Liga Hrvatska",
"Serie A TIM",
"Liga Hrvatska",
"MLS",
"LIGA BBVA MX",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"Premier League",
"Hellas Liga",
"LaLiga Santander",
"EFL Championship",
"Eredivisie",
"Ligue 1 Uber Eats",
"Meiji Yasuda J1",
"Bundesliga",
"A-League",
"Premier League",
"Ligue 1 Uber Eats",
"1A Pro League",
"Serie A TIM",
"CSL",
"Premier League",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Premier League",
"LIGA BBVA MX",
"Česká Liga",
"Ligue 1 Uber Eats",
"LaLiga SmartBank",
"Ligue 1 Uber Eats",
"Bundesliga",
"Hellas Liga",
"Liga Portugal",
"Süper Lig",
"LIGA BBVA MX",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"Premier League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"Bundesliga 2",
"Serie A TIM",
"Liga Portugal",
"LaLiga Santander",
"Süper Lig",
"Premier League",
"MLS",
"Süper Lig",
"LaLiga SmartBank",
"Hellas Liga",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Bundesliga",
"Serie A TIM",
"Bundesliga",
"Bundesliga",
"Bundesliga",
"Bundesliga 2",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Bundesliga",
"Serie A TIM",
"Premier League",
"Ligue 1 Uber Eats",
"Eredivisie",
"Eredivisie",
"3F Superliga",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"LIGA BBVA MX",
"LaLiga Santander",
"Eredivisie",
"Ligue 1 Uber Eats",
"Premier League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Serie A TIM",
"LaLiga Santander",
"Bundesliga",
"LaLiga Santander",
"1A Pro League",
"Premier League",
"Premier League",
"Serie A TIM",
"Bundesliga",
"LaLiga SmartBank",
"MLS",
"League of Russia",
"League of Russia",
"Süper Lig",
"LaLiga SmartBank",
"Süper Lig",
"Süper Lig",
"Premier League",
"Süper Lig",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Bundesliga",
"Premier League",
"Serie A TIM",
"Ö. Bundesliga",
"Serie A TIM",
"Süper Lig",
"Serie A TIM",
"Premier League",
"Premier League",
"3F Superliga",
"Premier League",
"A-League",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Süper Lig",
"LIGA BBVA MX",
"CSSL",
"cinch Prem",
"Süper Lig",
"Süper Lig",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Liga Hrvatska",
"LaLiga Santander",
"Eredivisie",
"LaLiga Santander",
"LIGA BBVA MX",
"MBS Pro League",
"Serie A TIM",
"LIGA BBVA MX",
"Süper Lig",
"EFL Championship",
"LaLiga Santander",
"Süper Lig",
"Süper Lig",
"CSSL",
"MBS Pro League",
"Premier League",
"Serie A TIM",
"MBS Pro League",
"Serie A TIM",
"LaLiga SmartBank",
"MBS Pro League",
"Serie A TIM",
"Serie A TIM",
"Ligue 1 Uber Eats",
"League of Russia",
"Serie A TIM",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"LIGA BBVA MX",
"LIGA BBVA MX",
"LIGA BBVA MX",
"Serie A TIM",
"LIGA BBVA MX",
"Hellas Liga",
"Ö. Bundesliga",
"Bundesliga 2",
"Calcio B",
"MBS Pro League",
"Süper Lig",
"Serie A TIM",
"Süper Lig",
"Ligue 1 Uber Eats",
"Süper Lig",
"Süper Lig",
"Magyar Liga",
"LaLiga Santander",
"Česká Liga",
"Bundesliga",
"Ligue 1 Uber Eats",
"Ukrayina Liha",
"Česká Liga",
"Süper Lig",
"Süper Lig",
"Ligue 1 Uber Eats",
"Liga Portugal",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"1A Pro League",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"Česká Liga",
"Premier League",
"Serie A TIM",
"Bundesliga",
"Liga Portugal",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"Liga Portugal",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Premier League",
"Eredivisie",
"Premier League",
"Premier League",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Liga Portugal",
"LaLiga Santander",
"LaLiga Santander",
"cinch Prem",
"LaLiga SmartBank",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"League of Russia",
"Premier League",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga Santander",
"Liga Portugal",
"Bundesliga",
"Bundesliga",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"1A Pro League",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Süper Lig",
"Premier League",
"LaLiga Santander",
"Premier League",
"League of Russia",
"CSSL",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Premier League",
"MLS",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"PKO Ekstraklasa",
"CSSL",
"Premier League",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Ö. Bundesliga",
"LPF",
"Premier League",
"MBS Pro League",
"LaLiga SmartBank",
"Liga Portugal",
"Eredivisie",
"EFL Championship",
"LaLiga SmartBank",
"LaLiga Santander",
"League of Russia",
"LaLiga Santander",
"Bundesliga",
"MLS",
"LIGA BBVA MX",
"LIGA BBVA MX",
"Liga Portugal",
"Premier League",
"LIGA BBVA MX",
"Eredivisie",
"Serie A TIM",
"1A Pro League",
"LaLiga Santander",
"Serie A TIM",
"Bundesliga",
"Liga Portugal",
"Hellas Liga",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"League of Russia",
"Ligue 1 Uber Eats",
"Süper Lig",
"MBS Pro League",
"Süper Lig",
"Premier League",
"LIGA BBVA MX",
"Ligue 1 Uber Eats",
"Premier League",
"MBS Pro League",
"Bundesliga",
"Premier League",
"LIGA BBVA MX",
"Premier League",
"Premier League",
"LaLiga SmartBank",
"League of Russia",
"Serie A TIM",
"Serie A TIM",
"Liga Portugal",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Premier League",
"LaLiga Santander",
"LPF",
"Ligue 1 Uber Eats",
"Bundesliga",
"EFL Championship",
"Premier League",
"League of Russia",
"Serie A TIM",
"Hellas Liga",
"Serie A TIM",
"Bundesliga",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"LaLiga Santander",
"Premier League",
"Ligue 2 BKT",
"Bundesliga",
"Ligue 1 Uber Eats",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"LaLiga SmartBank",
"Hellas Liga",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"Premier League",
"MLS",
"LaLiga Santander",
"LaLiga Santander",
"Ukrayina Liha",
"Ligue 1 Uber Eats",
"EFL Championship",
"Premier League",
"Süper Lig",
"MBS Pro League",
"LaLiga Santander",
"Ligue 1 Uber Eats",
"LIGA BBVA MX",
"Liga Portugal",
"LIGA BBVA MX",
"Serie A TIM",
"Süper Lig",
"1A Pro League",
"LIGA BBVA MX",
"Liga Portugal",
"Bundesliga",
"LaLiga Santander",
"Bundesliga",
"Bundesliga",
"EFL Championship",
"Bundesliga",
"Premier League",
"EFL Championship",
"Süper Lig",
"Bundesliga",
"EFL Championship",
"LaLiga Santander",
"LPF",
"LaLiga Santander",
"LIGA BBVA MX",
"1A Pro League",
"Liga Portugal",
"1A Pro League",
"Premier League",
"cinch Prem",
"Serie A TIM",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Serie A TIM",
"Ligue 1 Uber Eats",
"3F Superliga",
"Bundesliga",
"Bundesliga",
"LaLiga Santander",
"LaLiga Santander",
"MLS",
"MLS",
"MBS Pro League",
"Premier League",
"CSSL",
"Ukrayina Liha",
"CSL",
"Ligue 1 Uber Eats",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"MLS",
"cinch Prem",
"Meiji Yasuda J1",
"Premier League",
"LIGA BBVA MX",
"Premier League",
"Serie A TIM",
"Premier League",
"Premier League",
"Calcio B",
"MBS Pro League",
"Premier League",
"1A Pro League",
"Süper Lig",
"Premier League",
"Liga Hrvatska",
"MLS",
"Liga Hrvatska",
"Serie A TIM",
"Serie A TIM",
"Bundesliga",
"Süper Lig",
"Serie A TIM",
"MBS Pro League",
"EFL Championship",
"LIGA BBVA MX",
"Hellas Liga",
"Bundesliga",
"Serie A TIM",
"Ligue 1 Uber Eats",
"Premier League",
"Premier League",
"Bundesliga 2",
"Liga Portugal",
"Serie A TIM",
"Premier League",
"LaLiga Santander",
"Bundesliga",
"Serie A TIM",
"Premier League",
"cinch Prem",
"LaLiga SmartBank",
"Serie A TIM",
"Bundesliga",
"Eredivisie",
"Serie A TIM",
"LaLiga SmartBank",
"Allsvenskan",
"Liga Portugal",
"LaLiga Santander",
"LaLiga SmartBank",
"Premier League",
"Premier League",
"Serie A TIM",
"LaLiga Santander",
"LaLiga SmartBank",
"Premier League",
"LaLiga Santander",
"Premier League",
"Serie A TIM",
"EFL Championship",
"Bundesliga",
"LaLiga Santander",
"Premier League",
"Süper Lig",
"Eredivisie",
"Serie A TIM",
"Ligue 1 Uber Eats",
"LaLiga Santander",
"Süper Lig",
"K League 1",
"Serie A TIM",
"LIGA BBVA MX",
"Premier League",
"Süper Lig",
"Premier League",
"Premier League",
"LaLiga Santander",
"Hellas Liga",
"Premier League",
"Serie A TIM",
"Premier League",
"Bundesliga",
"CSL",
"cinch Prem",
"EFL Championship",
"Premier League",
"Süper Lig",
"MLS",
"Česká Liga",
"Premier League",
"LaLiga SmartBank",
"LIGA BBVA MX",
"Süper Lig",
"League of Russia",
"Serie A TIM",
"Premier League",
"MBS Pro League",
"Süper Lig",
"MLS",
"Hellas Liga",
"Ligue 1 Uber Eats",
"Liga Portugal",
"CSL",
"Premier League",
"MLS",
"Bundesliga 2",
"Bundesliga",
"Premier League",
"MBS Pro League",
"Ligue 1 Uber Eats",
"Premier League",
"Česká Liga",
"Premier League",
"MLS",
"Serie A TIM",
"Süper Lig",
"Liga Portugal",
"CSL",
"Hellas Liga",
"Ligue 1 Uber Eats",
"CSSL",
"CSL",
"Allsvenskan",
"LaLiga SmartBank",
"1A Pro League",
"Premier League",
"Premier League",
"Premier League",
"LIGA BBVA MX",
"1A Pro League",
"Ligue 2 BKT",
"LaLiga Santander",
"Meiji Yasuda J1",
"Eliteserien",
"Premier League",
"Serie A TIM",
"LaLiga Santander"
]